/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Health */
        get: operations["get_health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/datasets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Datasets */
        get: operations["list_datasets_datasets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/datasets/{dataset_version_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dataset */
        get: operations["get_dataset_datasets__dataset_version_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/datasets/{dataset_version_id}/validation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dataset Validation */
        get: operations["get_dataset_validation_datasets__dataset_version_id__validation_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/datasets/{dataset_version_id}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Activate Version
         * @description Make this version the one queries count for its dataset.
         */
        post: operations["activate_version_datasets__dataset_version_id__activate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/datasets/{dataset_version_id}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Deactivate Version
         * @description Stop counting this version, returning the dataset to the build's.
         */
        post: operations["deactivate_version_datasets__dataset_version_id__deactivate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/datasets/{dataset_version_id}/layers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Dataset Layers
         * @description Row counts per storage layer, and what happened between them.
         */
        get: operations["get_dataset_layers_datasets__dataset_version_id__layers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/datasets/{dataset_version_id}/validation/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Validation Summary
         * @description Finding counts per rule for one dataset version.
         */
        get: operations["get_validation_summary_datasets__dataset_version_id__validation_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lineage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Lineage For Many
         * @description Lineage for several versions at once.
         *
         *     Takes the ``dataset_version_id`` values straight from a query response's
         *     ``applied_context.source_datasets``, so "where did this chart come from" is
         *     one call rather than one per dataset.
         */
        get: operations["get_lineage_for_many_lineage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lineage/{dataset_version_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Lineage */
        get: operations["get_lineage_lineage__dataset_version_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingest/schemas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Ingest Schemas
         * @description The declared schemas an upload can be validated against.
         */
        get: operations["list_ingest_schemas_ingest_schemas_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingest/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest Upload
         * @description Validate an uploaded file against a known dataset's schema and rules.
         *
         *     An empty ``dataset_name`` means the file matches no declared schema: it is
         *     still read and validated, for the problems that hold for any table.
         *
         *     Bad rows are quarantined and reported; the request succeeds regardless, so
         *     the demo can show findings rather than an error page.
         */
        post: operations["ingest_upload_ingest_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/semantic/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Metrics */
        get: operations["list_metrics_semantic_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/semantic/dimensions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Dimensions */
        get: operations["list_dimensions_semantic_dimensions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/semantic/dimensions/{dimension_id}/values": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Dimension Values */
        get: operations["list_dimension_values_semantic_dimensions__dimension_id__values_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Query
         * @description Run a query spec. Rows always arrive with their context and caveats.
         */
        post: operations["post_query_query_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/query/records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Query Records
         * @description The supporting fact rows behind a result, each with its source file.
         */
        post: operations["post_query_records_query_records_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/query/narrative-facts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Narrative Facts
         * @description One precomputed bundle for a dashboard view: totals, movement, leaders,
         *     laggards, largest changes and anomalies, plus the caveats that apply.
         *
         *     Pure SQL. The GenAI step writes prose from this and does no arithmetic.
         */
        post: operations["post_narrative_facts_query_narrative_facts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Export
         * @description Produce a file and record it, synchronously.
         *
         *     A request carrying a query spec has its context derived from running that
         *     spec here; one carrying an inline payload says so inside the file.
         */
        post: operations["create_export_export_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exports/limits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Export Limits
         * @description The row ceiling, so the export dialog warns with the figure that applies.
         */
        get: operations["get_export_limits_exports_limits_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Exports */
        get: operations["list_exports_exports_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/export/{export_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Export */
        get: operations["get_export_export__export_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/export/{export_id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download Export
         * @description The file itself, named as it was generated.
         */
        get: operations["download_export_export__export_id__download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sandbox/model-config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Sandbox Model Config
         * @description The model configuration as the model service states it, each field sourced.
         */
        get: operations["get_sandbox_model_config_sandbox_model_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sandbox/datasets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Sandbox Datasets
         * @description Every dataset, with its compatibility against the model's request.
         */
        get: operations["list_sandbox_datasets_sandbox_datasets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sandbox/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Sandbox Run
         * @description Run the pre-trained model over a dataset; returns when the run has ended.
         *
         *     Several hundred model calls take a while, so they run off the event loop on
         *     their own cursor. This is not a background job: the request waits.
         */
        post: operations["create_sandbox_run_sandbox_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sandbox/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Sandbox Run Status
         * @description Check the status and progress of a sandbox run.
         */
        get: operations["get_sandbox_run_status_sandbox_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sandbox/runs/{run_id}/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Sandbox Run Results
         * @description Retrieve full evaluation metrics, feature importance, and sample predictions.
         */
        get: operations["get_sandbox_run_results_sandbox_runs__run_id__results_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sandbox/runs/{run_id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Save Sandbox Version
         * @description Save a run as a named model version for governance.
         */
        post: operations["save_sandbox_version_sandbox_runs__run_id__versions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sandbox/versions/{version_id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Publish Sandbox Version
         * @description Publish a model version's forecasts to the dashboard and record lineage.
         */
        post: operations["publish_sandbox_version_sandbox_versions__version_id__publish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/forecasts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Dashboard Forecasts
         * @description Retrieve published crop-yield forecasts with actual-vs-forecast comparison.
         */
        get: operations["get_dashboard_forecasts_dashboard_forecasts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assistant/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Assistant Questions
         * @description Starter questions, answered from the shipped cache with no API key.
         */
        get: operations["list_assistant_questions_assistant_questions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assistant/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask Assistant
         * @description A free-text question, answered from the loaded data or declined.
         *
         *     A model call can take seconds, so it runs off the event loop on its own
         *     cursor rather than holding every other request behind it.
         */
        post: operations["ask_assistant_assistant_ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/narrative/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Dashboard Narrative
         * @description "What this view shows": prose over the view's SQL fact bundle.
         *
         *     Written by the model when one is available and its figures check out;
         *     otherwise rendered from the same facts by a template, and labelled so.
         */
        post: operations["dashboard_narrative_narrative_dashboard_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActivationResult
         * @description Which version now feeds the facts for a dataset.
         */
        ActivationResult: {
            /** Dataset Name */
            dataset_name: string;
            /** Activated */
            activated?: string | null;
            /** Deactivated */
            deactivated?: string[];
        };
        /** ActualVsPredicted */
        ActualVsPredicted: {
            /** District Name */
            district_name: string;
            /** Crop Name */
            crop_name: string;
            /** Actual */
            actual: number;
            /** Predicted */
            predicted: number;
            /** Residual */
            residual: number;
        };
        /**
         * AppliedContext
         * @description What was asked, what was read, and how much of it.
         */
        AppliedContext: {
            /** Metric */
            metric: string;
            /** Metric Label */
            metric_label: string;
            /** Unit */
            unit: string;
            /** Dimensions */
            dimensions: string[];
            /** Filters */
            filters: {
                [key: string]: unknown;
            }[];
            /** Period */
            period?: {
                [key: string]: unknown;
            } | null;
            /** Relation */
            relation: string;
            /** Source Datasets */
            source_datasets: components["schemas"]["SourceDataset"][];
            /** Data Origin */
            data_origin: {
                [key: string]: number;
            };
            /** Grain Source */
            grain_source?: {
                [key: string]: number;
            };
            /** Row Count */
            row_count: number;
            /** Underlying Row Count */
            underlying_row_count: number;
            /** Generated At */
            generated_at: string;
            /** Provenance Notes */
            provenance_notes?: string[];
        };
        /** AskRequest */
        AskRequest: {
            /** Question */
            question: string;
        };
        /** AssistantAnswer */
        AssistantAnswer: {
            /** Question */
            question: string;
            /**
             * Status
             * @enum {string}
             */
            status: "answered" | "declined" | "unavailable";
            /** Answer */
            answer: string;
            /** Answer Source */
            answer_source?: ("model" | "template") | null;
            /** Limitation */
            limitation?: string | null;
            interpretation?: components["schemas"]["Interpretation"] | null;
            query_spec?: components["schemas"]["QuerySpec"] | null;
            chart_spec?: components["schemas"]["ChartSpec"] | null;
            /** Applied Filters */
            applied_filters: components["schemas"]["DescribedFilter"][];
            /** Source Datasets */
            source_datasets: components["schemas"]["SourceDataset"][];
            /** Period */
            period?: string | null;
            /** Rows */
            rows: {
                [key: string]: unknown;
            }[];
            /** Records Preview */
            records_preview: {
                [key: string]: unknown;
            }[];
            /** Records Total */
            records_total: number;
            /** Caveats */
            caveats: components["schemas"]["Caveat"][];
            applied_context?: components["schemas"]["AppliedContext"] | null;
            /** Data Origin */
            data_origin: {
                [key: string]: number;
            };
            /** Grain Source */
            grain_source: {
                [key: string]: number;
            };
            /** Provenance Notes */
            provenance_notes: string[];
            /** Llm Calls */
            llm_calls: components["schemas"]["LlmCall"][];
            /** Served From Cache */
            served_from_cache: boolean;
        };
        /** Body_ingest_upload_ingest_upload_post */
        Body_ingest_upload_ingest_upload_post: {
            /** File */
            file: string;
            /**
             * Dataset Name
             * @default
             */
            dataset_name: string;
            /**
             * Data Origin
             * @default
             */
            data_origin: string;
        };
        /** Caveat */
        Caveat: {
            /** Code */
            code: string;
            /** Severity */
            severity: string;
            /** Message */
            message: string;
            /** Affected Rows */
            affected_rows: number;
        };
        /** ChartSpec */
        ChartSpec: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "bar" | "line";
            /** X Key */
            x_key: string;
            /** Y Key */
            y_key: string;
            /** Unit */
            unit: string;
            /** Series Label */
            series_label: string;
            /** Data */
            data: {
                [key: string]: unknown;
            }[];
        };
        /** CreateRunRequest */
        CreateRunRequest: {
            /** Dataset Id */
            dataset_id: string;
            /**
             * Use Case
             * @default minor_crop_yield
             * @constant
             */
            use_case: "minor_crop_yield";
        };
        /** DashboardNarrative */
        DashboardNarrative: {
            /** Narrative */
            narrative: string;
            /**
             * Narrative Source
             * @enum {string}
             */
            narrative_source: "model" | "template";
            /** Model */
            model?: string | null;
            /** Facts Used */
            facts_used: components["schemas"]["NarrativeFact"][];
            /** Caveats */
            caveats: components["schemas"]["Caveat"][];
            applied_context: components["schemas"]["AppliedContext"];
            /** Data Origin */
            data_origin: {
                [key: string]: number;
            };
            /** Served From Cache */
            served_from_cache: boolean;
            /** Llm Calls */
            llm_calls: components["schemas"]["LlmCall"][];
        };
        /** DatasetVersion */
        DatasetVersion: {
            /** Dataset Version Id */
            dataset_version_id: string;
            /** Dataset Name */
            dataset_name: string;
            /** Source File */
            source_file: string;
            /** Source Type */
            source_type: string;
            /** Sha256 */
            sha256: string;
            /** Row Count */
            row_count: number;
            /** Layer */
            layer: string;
            /**
             * Loaded At
             * Format: date-time
             */
            loaded_at: string;
            /** Generator Version */
            generator_version?: string | null;
            /**
             * Is Active
             * @description Whether queries count this version. Exactly one version per dataset is active; an upload starts inactive.
             * @default true
             */
            is_active: boolean;
        };
        /**
         * DescribedFilter
         * @description A filter as applied, with the master's display names beside its codes.
         */
        DescribedFilter: {
            /** Dimension */
            dimension: string;
            /** Op */
            op: string;
            /** Values */
            values: string[];
            /** Dimension Label */
            dimension_label: string;
            /** Values Display */
            values_display: string[];
        };
        /** DimensionInfo */
        DimensionInfo: {
            /** Dimension Id */
            dimension_id: string;
            /** Label */
            label: string;
            /** Description */
            description: string;
            /** Value Type */
            value_type: string;
            /** Is Coded */
            is_coded: boolean;
            /** Available On */
            available_on: string[];
        };
        /** DimensionRef */
        DimensionRef: {
            /** Id */
            id: string;
            /** Label */
            label: string;
        };
        /** DimensionValue */
        DimensionValue: {
            /** Value */
            value: string;
            /** Label */
            label: string;
        };
        /** DomainCount */
        DomainCount: {
            /** Reason */
            reason: string;
            /** Count */
            count: number;
        };
        /**
         * ExportLimits
         * @description Limits the export service enforces.
         */
        ExportLimits: {
            /** Row Ceiling */
            row_ceiling: number;
        };
        /**
         * ExportOptions
         * @description What the caller wants inside the file.
         */
        ExportOptions: {
            /**
             * Include Context
             * @default true
             */
            include_context: boolean;
            /**
             * Include Caveats
             * @default true
             */
            include_caveats: boolean;
            /**
             * Include Records
             * @default true
             */
            include_records: boolean;
        };
        /**
         * ExportPayload
         * @description Rows and context for a surface that has no query spec yet.
         *
         *     The assistant and the sandbox are still fixture-backed, so their exports
         *     cannot be reproduced from a spec. A file built this way says so.
         */
        ExportPayload: {
            /** Rows */
            rows?: {
                [key: string]: unknown;
            }[];
            /** Context */
            context?: {
                [key: string]: unknown;
            };
            /** Caveats */
            caveats?: components["schemas"]["Caveat"][];
        };
        /**
         * ExportRecord
         * @description One produced file, with the context it carries.
         */
        ExportRecord: {
            /** Export Id */
            export_id: string;
            /** Export Type */
            export_type: string;
            /** Format */
            format: string;
            /** Status */
            status: string;
            /** Filename */
            filename: string;
            /** Size Bytes */
            size_bytes: number;
            /** Created At */
            created_at: string;
            context: components["schemas"]["ExportedContext"];
        };
        /** ExportRequest */
        ExportRequest: {
            /**
             * Export Type
             * @enum {string}
             */
            export_type: "dashboard_panel" | "records_grid" | "assistant_answer" | "model_output" | "narrative";
            /**
             * Format
             * @enum {string}
             */
            format: "csv" | "xlsx" | "pdf" | "json" | "png";
            /** Panel Title */
            panel_title: string;
            query_spec?: components["schemas"]["QuerySpec"] | null;
            payload?: components["schemas"]["ExportPayload"] | null;
            options?: components["schemas"]["ExportOptions"];
        };
        /**
         * ExportedContext
         * @description The context written into an export file and shown on the Exports screen.
         *
         *     A superset of :class:`AppliedContext`: it adds what the file needs and the
         *     query does not have -- which panel asked, how the context was obtained, the
         *     disclosure lines, the caveats and a period phrase a reader can read. Every
         *     field is optional except the panel, because an export of a surface with no
         *     query spec has fewer of them and must not pretend otherwise.
         */
        ExportedContext: {
            /** Panel Title */
            panel_title: string;
            /** Metric */
            metric?: string | null;
            /** Metric Label */
            metric_label?: string | null;
            /** Unit */
            unit?: string | null;
            /** Dimensions */
            dimensions?: string[];
            /** Filters */
            filters?: {
                [key: string]: unknown;
            }[];
            /** Period */
            period?: {
                [key: string]: unknown;
            } | null;
            /** Period Label */
            period_label?: string | null;
            /** Relation */
            relation?: string | null;
            /** Source Datasets */
            source_datasets?: components["schemas"]["SourceDataset"][];
            /** Data Origin */
            data_origin?: {
                [key: string]: number;
            };
            /** Grain Source */
            grain_source?: {
                [key: string]: number;
            };
            /**
             * Row Count
             * @default 0
             */
            row_count: number;
            /**
             * Underlying Row Count
             * @default 0
             */
            underlying_row_count: number;
            /**
             * Truncated
             * @default false
             */
            truncated: boolean;
            /** Matching Row Count */
            matching_row_count?: number | null;
            /** Provenance Notes */
            provenance_notes?: string[];
            /** Caveats */
            caveats?: components["schemas"]["Caveat"][];
            /**
             * Context Origin
             * @default derived
             */
            context_origin: string;
            /** Generated At */
            generated_at?: string | null;
            /** Model Configurations */
            model_configurations?: {
                [key: string]: string;
            }[];
        };
        /** FeatureImportance */
        FeatureImportance: {
            /** Feature */
            feature: string;
            /** Label */
            label: string;
            /** Weight */
            weight: number;
        };
        /** Filter */
        Filter: {
            /** Dimension */
            dimension: string;
            /**
             * Op
             * @default in
             * @enum {string}
             */
            op: "eq" | "in" | "not_in" | "between" | "gte" | "lte";
            /** Values */
            values: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /** Status */
            status: string;
            /** Database */
            database: string;
            /** Database Present */
            database_present: boolean;
            /** Fact Rows */
            fact_rows: {
                [key: string]: number;
            };
            /** Last Run Id */
            last_run_id?: string | null;
            /** Last Run Status */
            last_run_status?: string | null;
            /** Schema Version */
            schema_version?: number | null;
        };
        /**
         * IngestResult
         * @description Outcome of POST /ingest/upload -- findings, never an exception.
         */
        IngestResult: {
            /** Run Id */
            run_id: string;
            /** Dataset Name */
            dataset_name: string;
            /** Dataset Version Id */
            dataset_version_id: string;
            /** Filename */
            filename: string;
            /** Data Origin */
            data_origin: string;
            /** Rows Read */
            rows_read: number;
            /**
             * Rows Staged
             * @description Rows written to the upload's staging table; 0 when nothing was staged.
             */
            rows_staged: number;
            /**
             * Rows Promoted
             * @description Rows appended to the analytics fact table under this version.
             * @default 0
             */
            rows_promoted: number;
            /** Rows Quarantined */
            rows_quarantined: number;
            /** Error Count */
            error_count: number;
            /** Warning Count */
            warning_count: number;
            /** Info Count */
            info_count: number;
            /** Findings By Rule */
            findings_by_rule: components["schemas"]["RuleCount"][];
            /**
             * Findings
             * @description Capped at findings_limit; the full set is queryable at /datasets/{dataset_version_id}/validation
             */
            findings: components["schemas"]["ValidationFinding"][];
            /** Quarantine Table */
            quarantine_table?: string | null;
            /** Staging Table */
            staging_table?: string | null;
            /** Promoted To */
            promoted_to?: string | null;
            /**
             * Duplicate Of
             * @description Set when these exact bytes are already loaded. Nothing was written: the named version already describes this content.
             */
            duplicate_of?: string | null;
            /**
             * Duplicate Layer
             * @description Which layer created the version already holding it.
             */
            duplicate_layer?: string | null;
        };
        /**
         * IngestSchema
         * @description The declared shape an uploaded file is validated against.
         *
         *     Lets the ingest screen match a file's own header to the right dataset
         *     instead of guessing, so a mismatch is reported rather than stumbled into.
         */
        IngestSchema: {
            /** Dataset Name */
            dataset_name: string;
            /** Source Type */
            source_type: string;
            /** Expected Columns */
            expected_columns: string[];
        };
        /**
         * InputSummary
         * @description A dataset's combinations checked against the model's input domains.
         */
        InputSummary: {
            /** Agri Years */
            agri_years: string[];
            /** Combinations */
            combinations: number;
            /** Sent */
            sent: number;
            /** Out Of Domain */
            out_of_domain: components["schemas"]["DomainCount"][];
            /** Rule */
            rule: string;
        };
        /**
         * Interpretation
         * @description How the question was read: the query the model chose, after validation.
         */
        Interpretation: {
            /** Metric */
            metric: string;
            /** Metric Label */
            metric_label: string;
            /** Unit */
            unit: string;
            /** Dimensions */
            dimensions: components["schemas"]["DimensionRef"][];
            /** Filters */
            filters: components["schemas"]["DescribedFilter"][];
            /** Period */
            period?: string | null;
            /** Order */
            order?: string | null;
            /** Limit */
            limit: number;
            /** Corrected */
            corrected: boolean;
            /** Model */
            model: string;
        };
        /**
         * LayerStage
         * @description One hop of a dataset's journey through the storage layers.
         */
        LayerStage: {
            /** Layer */
            layer: string;
            /** Label */
            label: string;
            /** Table */
            table?: string | null;
            /** Row Count */
            row_count: number;
            /** Purpose */
            purpose: string;
            /** Transition */
            transition: string;
        };
        /** Lineage */
        Lineage: {
            /** Dataset Version Id */
            dataset_version_id: string;
            /** Dataset Name */
            dataset_name: string;
            /** Source File */
            source_file: string;
            /** Edges */
            edges: components["schemas"]["LineageEdge"][];
        };
        /** LineageEdge */
        LineageEdge: {
            /** From Node */
            from_node: string;
            /** To Node */
            to_node: string;
            /** Edge Type */
            edge_type: string;
            /** Dataset Version Id */
            dataset_version_id: string;
        };
        /** LlmCall */
        LlmCall: {
            /** Purpose */
            purpose: string;
            /** Model */
            model: string;
            /** Served From Cache */
            served_from_cache: boolean;
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "ok" | "unavailable" | "error";
            /** Error */
            error?: string | null;
        };
        /** MetricInfo */
        MetricInfo: {
            /** Metric Id */
            metric_id: string;
            /** Label */
            label: string;
            /** Unit */
            unit: string;
            /** Definition */
            definition: string;
            /** Allowed Dimensions */
            allowed_dimensions: string[];
            /** Required Dimensions */
            required_dimensions: string[];
            /** Forbidden Dimensions */
            forbidden_dimensions: string[];
            /** Requires Scope */
            requires_scope: string[];
            /** Default Aggregation */
            default_aggregation: string;
            /** Facts */
            facts: string[];
        };
        /** MetricSet */
        MetricSet: {
            /** R2 */
            r2?: number | null;
            /** Rmse */
            rmse: number;
            /** Mae */
            mae: number;
            /** N */
            n: number;
        };
        /** MissingField */
        MissingField: {
            /** Field */
            field: string;
            /** Reason */
            reason: string;
        };
        /** ModelConfig */
        ModelConfig: {
            /** Service Url */
            service_url: string;
            /** Fetched At */
            fetched_at: string;
            model_name: components["schemas"]["StatedText"];
            target: components["schemas"]["StatedText"];
            model_version: components["schemas"]["StatedText"];
            training_period: components["schemas"]["StatedText"];
            features: components["schemas"]["StatedFeatures"];
            input_domains: components["schemas"]["StatedDomains"];
        };
        /** ModelFeature */
        ModelFeature: {
            /** Name */
            name: string;
            /** Type */
            type: string;
            /** Description */
            description: string;
        };
        /**
         * NarrativeFact
         * @description One figure the narrative may quote, computed in SQL.
         */
        NarrativeFact: {
            /** Label */
            label: string;
            /** Value */
            value?: number | null;
            /** Unit */
            unit: string;
            /** Scope */
            scope?: string | null;
        };
        /**
         * NarrativeFactsResponse
         * @description Everything a narrative may assert, precomputed so the LLM does no maths.
         */
        NarrativeFactsResponse: {
            /** Headline */
            headline: {
                [key: string]: unknown;
            };
            /** Movement */
            movement?: {
                [key: string]: unknown;
            } | null;
            /** Leaders */
            leaders: {
                [key: string]: unknown;
            }[];
            /** Laggards */
            laggards: {
                [key: string]: unknown;
            }[];
            /** Largest Changes */
            largest_changes: {
                [key: string]: unknown;
            }[];
            /** Anomalies */
            anomalies: {
                [key: string]: unknown;
            }[];
            applied_context: components["schemas"]["AppliedContext"];
            /** Caveats */
            caveats: components["schemas"]["Caveat"][];
        };
        /** NarrativeRequest */
        NarrativeRequest: {
            query_spec: components["schemas"]["QuerySpec"];
        };
        /** OrderBy */
        OrderBy: {
            /**
             * Field
             * @default value
             */
            field: string;
            /**
             * Direction
             * @default desc
             * @enum {string}
             */
            direction: "asc" | "desc";
        };
        /** Page[DatasetVersion] */
        Page_DatasetVersion_: {
            /** Items */
            items: components["schemas"]["DatasetVersion"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
        };
        /** Page[DimensionInfo] */
        Page_DimensionInfo_: {
            /** Items */
            items: components["schemas"]["DimensionInfo"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
        };
        /** Page[DimensionValue] */
        Page_DimensionValue_: {
            /** Items */
            items: components["schemas"]["DimensionValue"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
        };
        /** Page[ExportRecord] */
        Page_ExportRecord_: {
            /** Items */
            items: components["schemas"]["ExportRecord"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
        };
        /** Page[IngestSchema] */
        Page_IngestSchema_: {
            /** Items */
            items: components["schemas"]["IngestSchema"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
        };
        /** Page[LayerStage] */
        Page_LayerStage_: {
            /** Items */
            items: components["schemas"]["LayerStage"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
        };
        /** Page[Lineage] */
        Page_Lineage_: {
            /** Items */
            items: components["schemas"]["Lineage"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
        };
        /** Page[MetricInfo] */
        Page_MetricInfo_: {
            /** Items */
            items: components["schemas"]["MetricInfo"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
        };
        /** Page[RuleSummary] */
        Page_RuleSummary_: {
            /** Items */
            items: components["schemas"]["RuleSummary"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
        };
        /** Page[StarterQuestion] */
        Page_StarterQuestion_: {
            /** Items */
            items: components["schemas"]["StarterQuestion"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
        };
        /** Page[ValidationFinding] */
        Page_ValidationFinding_: {
            /** Items */
            items: components["schemas"]["ValidationFinding"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
        };
        /** PerCropMetric */
        PerCropMetric: {
            /** R2 */
            r2?: number | null;
            /** Rmse */
            rmse: number;
            /** Mae */
            mae: number;
            /** N */
            n: number;
            /** Crop Id */
            crop_id: string;
            /** Crop Name */
            crop_name: string;
        };
        /**
         * Period
         * @description Inclusive agricultural-year range, e.g. 2022-23 to 2024-25.
         */
        Period: {
            /** From */
            from?: string | null;
            /** To */
            to?: string | null;
        };
        /** PredictionRow */
        PredictionRow: {
            /** District Id */
            district_id: string;
            /** District Name */
            district_name: string;
            /** Crop Id */
            crop_id: string;
            /** Crop Name */
            crop_name: string;
            /** Season */
            season: string;
            /** Agri Year */
            agri_year: string;
            /** Area Ha */
            area_ha: number;
            /** Predicted Yield Qtl Per Ha */
            predicted_yield_qtl_per_ha: number;
            /** Estimated Production Qtls */
            estimated_production_qtls: number;
            /**
             * Output Label
             * @default Analytical Estimates
             */
            output_label: string;
            /** Actual Yield Qtl Per Ha */
            actual_yield_qtl_per_ha?: number | null;
        };
        /** PublishVersionResponse */
        PublishVersionResponse: {
            /** Version Id */
            version_id: string;
            /**
             * Published
             * @default true
             */
            published: boolean;
        };
        /** PublishedForecast */
        PublishedForecast: {
            /** Crop Id */
            crop_id: string;
            /** Crop Name */
            crop_name: string;
            /** District Id */
            district_id: string;
            /** District Name */
            district_name: string;
            /** Season */
            season: string;
            /** Agri Year */
            agri_year: string;
            /** Actual Yield */
            actual_yield?: number | null;
            /** Forecast Yield */
            forecast_yield: number;
            /**
             * Unit
             * @default qtl/ha
             */
            unit: string;
            /** Version Id */
            version_id: string;
            /**
             * Output Label
             * @default Analytical Estimates
             */
            output_label: string;
            /** Model Config Hash */
            model_config_hash?: string | null;
            /** Data Origin */
            data_origin: {
                [key: string]: number;
            };
        };
        /** QueryResponse */
        QueryResponse: {
            /** Rows */
            rows: {
                [key: string]: unknown;
            }[];
            applied_context: components["schemas"]["AppliedContext"];
            /** Caveats */
            caveats: components["schemas"]["Caveat"][];
            /** Records */
            records?: {
                [key: string]: unknown;
            }[] | null;
        };
        /** QuerySpec */
        QuerySpec: {
            /** Metric */
            metric: string;
            /** Dimensions */
            dimensions?: string[];
            /** Filters */
            filters?: components["schemas"]["Filter"][];
            period?: components["schemas"]["Period"] | null;
            order_by?: components["schemas"]["OrderBy"] | null;
            /**
             * Limit
             * @default 100
             */
            limit: number;
            /**
             * Include Records
             * @default false
             */
            include_records: boolean;
        };
        /**
         * RecordsResponse
         * @description Drill-down: the fact rows behind a result cell.
         */
        RecordsResponse: {
            /** Records */
            records: {
                [key: string]: unknown;
            }[];
            /** Returned */
            returned: number;
            /** Total Matching */
            total_matching: number;
            /** Truncated */
            truncated: boolean;
            /** Source Datasets */
            source_datasets: components["schemas"]["SourceDataset"][];
        };
        /** RuleCount */
        RuleCount: {
            /** Rule Code */
            rule_code: string;
            /** Severity */
            severity: string;
            /** Count */
            count: number;
        };
        /**
         * RuleSummary
         * @description Findings for one rule within one dataset version.
         */
        RuleSummary: {
            /** Rule Code */
            rule_code: string;
            /** Severity */
            severity: string;
            /** Finding Count */
            finding_count: number;
            /** Sample Row Ref */
            sample_row_ref?: string | null;
            /** Sample Message */
            sample_message?: string | null;
            /** Column Count */
            column_count: number;
        };
        /** SandboxDataset */
        SandboxDataset: {
            /** Dataset Id */
            dataset_id: string;
            /** Label */
            label: string;
            /** Years */
            years: string;
            /** Row Count */
            row_count: number;
            /** Compatible */
            compatible?: boolean | null;
            /** Missing Fields */
            missing_fields: components["schemas"]["MissingField"][];
            input_summary?: components["schemas"]["InputSummary"] | null;
        };
        /** SandboxDatasetList */
        SandboxDatasetList: {
            /** Items */
            items: components["schemas"]["SandboxDataset"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
            /** Model Checked */
            model_checked: boolean;
            /** Message */
            message?: string | null;
        };
        /** SandboxModelConfig */
        SandboxModelConfig: {
            /** Checked */
            checked: boolean;
            /** Message */
            message?: string | null;
            config?: components["schemas"]["ModelConfig"] | null;
            /** Config Hash */
            config_hash?: string | null;
            use_case: components["schemas"]["SandboxUseCase"];
        };
        /** SandboxResults */
        SandboxResults: {
            /** Run Id */
            run_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "completed" | "completed_with_warnings";
            /** Warnings */
            warnings: string[];
            pooled?: components["schemas"]["MetricSet"] | null;
            /** Per Crop */
            per_crop: components["schemas"]["PerCropMetric"][];
            /** Actual Vs Predicted */
            actual_vs_predicted: components["schemas"]["ActualVsPredicted"][];
            /** Feature Importance */
            feature_importance: components["schemas"]["FeatureImportance"][];
            /** Explanation */
            explanation: string;
            /** Predictions */
            predictions: components["schemas"]["PredictionRow"][];
            /** Data Origin */
            data_origin: {
                [key: string]: number;
            };
            /**
             * Served From Cache
             * @default false
             */
            served_from_cache: boolean;
            /** Replayed From */
            replayed_from?: string | null;
            /** Replayed Run At */
            replayed_run_at?: string | null;
            model_configuration?: components["schemas"]["ModelConfig"] | null;
            /** Model Config Hash */
            model_config_hash?: string | null;
            /** Model Checked */
            model_checked: boolean;
            input_summary?: components["schemas"]["InputSummary"] | null;
            /** Agri Years */
            agri_years: string[];
            /** Comparison Label */
            comparison_label: string;
        };
        /** SandboxRunStatus */
        SandboxRunStatus: {
            /** Run Id */
            run_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "completed" | "completed_with_warnings" | "failed";
            /** Progress */
            progress: number;
            /** Message */
            message: string;
            /** Error Code */
            error_code?: string | null;
        };
        /** SandboxUseCase */
        SandboxUseCase: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Description */
            description: string;
            /** Fixed Reason */
            fixed_reason: string;
        };
        /** SandboxVersion */
        SandboxVersion: {
            /** Version Id */
            version_id: string;
            /** Run Id */
            run_id: string;
            /** Label */
            label: string;
            /** Created At */
            created_at: string;
            /** Published */
            published: boolean;
            /** Parameters */
            parameters: {
                [key: string]: string;
            };
        };
        /** SaveVersionRequest */
        SaveVersionRequest: {
            /** Label */
            label: string;
        };
        /** SourceDataset */
        SourceDataset: {
            /** Dataset Version Id */
            dataset_version_id: string;
            /** Dataset Name */
            dataset_name: string;
            /** Source File */
            source_file: string;
            /** Layer */
            layer: string;
        };
        /**
         * SpecErrorResponse
         * @description 422 body: machine-readable so a caller can correct itself and retry.
         */
        SpecErrorResponse: {
            /** Detail */
            detail: string;
            /** Code */
            code: string;
            /** Field */
            field: string;
            /** Allowed Values */
            allowed_values: string[];
        };
        /** StarterQuestion */
        StarterQuestion: {
            /** Question Id */
            question_id: string;
            /** Question */
            question: string;
        };
        /**
         * StatedDomains
         * @description The /metadata lists that bound what the model accepts. Input domains,
         *     not features: the features are the /predict request fields.
         */
        StatedDomains: {
            /** Value */
            value: {
                [key: string]: unknown;
            };
            /** Source */
            source: string;
        };
        /** StatedFeatures */
        StatedFeatures: {
            /** Value */
            value: components["schemas"]["ModelFeature"][];
            /** Source */
            source: string;
        };
        /**
         * StatedText
         * @description A value the model service stated, and the endpoint that stated it.
         *     Both None when the service does not state it: shown as not stated.
         */
        StatedText: {
            /** Value */
            value?: string | null;
            /** Source */
            source?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** ValidationFinding */
        ValidationFinding: {
            /** Run Id */
            run_id: string;
            /** Dataset Version Id */
            dataset_version_id: string;
            /** Rule Code */
            rule_code: string;
            /** Severity */
            severity: string;
            /** Row Ref */
            row_ref?: string | null;
            /** Column Name */
            column_name?: string | null;
            /** Message */
            message?: string | null;
            /** Observed Value */
            observed_value?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    list_datasets_datasets_get: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
                layer?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_DatasetVersion_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dataset_datasets__dataset_version_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_version_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetVersion"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dataset_validation_datasets__dataset_version_id__validation_get: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
                severity?: string | null;
                rule_code?: string | null;
            };
            header?: never;
            path: {
                dataset_version_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ValidationFinding_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    activate_version_datasets__dataset_version_id__activate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_version_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivationResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deactivate_version_datasets__dataset_version_id__deactivate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_version_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivationResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dataset_layers_datasets__dataset_version_id__layers_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_version_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_LayerStage_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_validation_summary_datasets__dataset_version_id__validation_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_version_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_RuleSummary_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_lineage_for_many_lineage_get: {
        parameters: {
            query: {
                dataset_version_id: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_Lineage_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_lineage_lineage__dataset_version_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_version_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lineage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_ingest_schemas_ingest_schemas_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_IngestSchema_"];
                };
            };
        };
    };
    ingest_upload_ingest_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_ingest_upload_ingest_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_metrics_semantic_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_MetricInfo_"];
                };
            };
        };
    };
    list_dimensions_semantic_dimensions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_DimensionInfo_"];
                };
            };
        };
    };
    list_dimension_values_semantic_dimensions__dimension_id__values_get: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path: {
                dimension_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_DimensionValue_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_query_query_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuerySpec"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpecErrorResponse"];
                };
            };
        };
    };
    post_query_records_query_records_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuerySpec"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordsResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpecErrorResponse"];
                };
            };
        };
    };
    post_narrative_facts_query_narrative_facts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuerySpec"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NarrativeFactsResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpecErrorResponse"];
                };
            };
        };
    };
    create_export_export_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportRecord"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpecErrorResponse"];
                };
            };
        };
    };
    get_export_limits_exports_limits_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportLimits"];
                };
            };
        };
    };
    list_exports_exports_get: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ExportRecord_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_export_export__export_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                export_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_export_export__export_id__download_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                export_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sandbox_model_config_sandbox_model_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SandboxModelConfig"];
                };
            };
        };
    };
    list_sandbox_datasets_sandbox_datasets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SandboxDatasetList"];
                };
            };
        };
    };
    create_sandbox_run_sandbox_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SandboxRunStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sandbox_run_status_sandbox_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SandboxRunStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sandbox_run_results_sandbox_runs__run_id__results_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SandboxResults"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_sandbox_version_sandbox_runs__run_id__versions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveVersionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SandboxVersion"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    publish_sandbox_version_sandbox_versions__version_id__publish_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublishVersionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dashboard_forecasts_dashboard_forecasts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublishedForecast"][];
                };
            };
        };
    };
    list_assistant_questions_assistant_questions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_StarterQuestion_"];
                };
            };
        };
    };
    ask_assistant_assistant_ask_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssistantAnswer"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dashboard_narrative_narrative_dashboard_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NarrativeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardNarrative"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpecErrorResponse"];
                };
            };
        };
    };
}
