/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Health */
        get: operations["get_health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/datasets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Datasets */
        get: operations["list_datasets_datasets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/datasets/{dataset_version_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dataset */
        get: operations["get_dataset_datasets__dataset_version_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/datasets/{dataset_version_id}/validation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dataset Validation */
        get: operations["get_dataset_validation_datasets__dataset_version_id__validation_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/datasets/{dataset_version_id}/layers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Dataset Layers
         * @description Row counts per storage layer, and what happened between them.
         */
        get: operations["get_dataset_layers_datasets__dataset_version_id__layers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/datasets/{dataset_version_id}/validation/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Validation Summary
         * @description Finding counts per rule for one dataset version.
         */
        get: operations["get_validation_summary_datasets__dataset_version_id__validation_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lineage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Lineage For Many
         * @description Lineage for several versions at once.
         *
         *     Takes the ``dataset_version_id`` values straight from a query response's
         *     ``applied_context.source_datasets``, so "where did this chart come from" is
         *     one call rather than one per dataset.
         */
        get: operations["get_lineage_for_many_lineage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lineage/{dataset_version_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Lineage */
        get: operations["get_lineage_lineage__dataset_version_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingest/schemas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Ingest Schemas
         * @description The declared schemas an upload can be validated against.
         */
        get: operations["list_ingest_schemas_ingest_schemas_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingest/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest Upload
         * @description Validate an uploaded file against a known dataset's schema and rules.
         *
         *     Bad rows are quarantined and reported; the request succeeds regardless, so
         *     the demo can show findings rather than an error page.
         */
        post: operations["ingest_upload_ingest_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/semantic/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Metrics */
        get: operations["list_metrics_semantic_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/semantic/dimensions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Dimensions */
        get: operations["list_dimensions_semantic_dimensions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/semantic/dimensions/{dimension_id}/values": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Dimension Values */
        get: operations["list_dimension_values_semantic_dimensions__dimension_id__values_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Query
         * @description Run a query spec. Rows always arrive with their context and caveats.
         */
        post: operations["post_query_query_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/query/records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Query Records
         * @description The supporting fact rows behind a result, each with its source file.
         */
        post: operations["post_query_records_query_records_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/query/narrative-facts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Narrative Facts
         * @description One precomputed bundle for a dashboard view: totals, movement, leaders,
         *     laggards, largest changes and anomalies, plus the caveats that apply.
         *
         *     Pure SQL. The GenAI step writes prose from this and does no arithmetic.
         */
        post: operations["post_narrative_facts_query_narrative_facts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AppliedContext
         * @description What was asked, what was read, and how much of it.
         */
        AppliedContext: {
            /** Metric */
            metric: string;
            /** Metric Label */
            metric_label: string;
            /** Unit */
            unit: string;
            /** Dimensions */
            dimensions: string[];
            /** Filters */
            filters: {
                [key: string]: unknown;
            }[];
            /** Period */
            period?: {
                [key: string]: unknown;
            } | null;
            /** Relation */
            relation: string;
            /** Source Datasets */
            source_datasets: components["schemas"]["SourceDataset"][];
            /** Data Origin */
            data_origin: {
                [key: string]: number;
            };
            /** Grain Source */
            grain_source?: {
                [key: string]: number;
            };
            /** Row Count */
            row_count: number;
            /** Underlying Row Count */
            underlying_row_count: number;
            /** Generated At */
            generated_at: string;
        };
        /** Body_ingest_upload_ingest_upload_post */
        Body_ingest_upload_ingest_upload_post: {
            /** Dataset Name */
            dataset_name: string;
            /** File */
            file: string;
        };
        /** Caveat */
        Caveat: {
            /** Code */
            code: string;
            /** Severity */
            severity: string;
            /** Message */
            message: string;
            /** Affected Rows */
            affected_rows: number;
        };
        /** DatasetVersion */
        DatasetVersion: {
            /** Dataset Version Id */
            dataset_version_id: string;
            /** Dataset Name */
            dataset_name: string;
            /** Source File */
            source_file: string;
            /** Source Type */
            source_type: string;
            /** Sha256 */
            sha256: string;
            /** Row Count */
            row_count: number;
            /** Layer */
            layer: string;
            /**
             * Loaded At
             * Format: date-time
             */
            loaded_at: string;
            /** Generator Version */
            generator_version?: string | null;
        };
        /** DimensionInfo */
        DimensionInfo: {
            /** Dimension Id */
            dimension_id: string;
            /** Label */
            label: string;
            /** Description */
            description: string;
            /** Value Type */
            value_type: string;
            /** Is Coded */
            is_coded: boolean;
            /** Available On */
            available_on: string[];
        };
        /** DimensionValue */
        DimensionValue: {
            /** Value */
            value: string;
            /** Label */
            label: string;
        };
        /** Filter */
        Filter: {
            /** Dimension */
            dimension: string;
            /**
             * Op
             * @default in
             * @enum {string}
             */
            op: "eq" | "in" | "not_in" | "between" | "gte" | "lte";
            /** Values */
            values: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /** Status */
            status: string;
            /** Database */
            database: string;
            /** Database Present */
            database_present: boolean;
            /** Fact Rows */
            fact_rows: {
                [key: string]: number;
            };
            /** Last Run Id */
            last_run_id?: string | null;
            /** Last Run Status */
            last_run_status?: string | null;
        };
        /**
         * IngestResult
         * @description Outcome of POST /ingest/upload -- findings, never an exception.
         */
        IngestResult: {
            /** Run Id */
            run_id: string;
            /** Dataset Name */
            dataset_name: string;
            /** Dataset Version Id */
            dataset_version_id: string;
            /** Filename */
            filename: string;
            /** Data Origin */
            data_origin: string;
            /** Rows Read */
            rows_read: number;
            /** Rows Staged */
            rows_staged: number;
            /** Rows Quarantined */
            rows_quarantined: number;
            /** Error Count */
            error_count: number;
            /** Warning Count */
            warning_count: number;
            /** Info Count */
            info_count: number;
            /** Findings By Rule */
            findings_by_rule: components["schemas"]["RuleCount"][];
            /**
             * Findings
             * @description Capped at findings_limit; the full set is queryable at /datasets/{dataset_version_id}/validation
             */
            findings: components["schemas"]["ValidationFinding"][];
            /** Quarantine Table */
            quarantine_table?: string | null;
        };
        /**
         * IngestSchema
         * @description The declared shape an uploaded file is validated against.
         *
         *     Lets the ingest screen match a file's own header to the right dataset
         *     instead of guessing, so a mismatch is reported rather than stumbled into.
         */
        IngestSchema: {
            /** Dataset Name */
            dataset_name: string;
            /** Source Type */
            source_type: string;
            /** Expected Columns */
            expected_columns: string[];
        };
        /**
         * LayerStage
         * @description One hop of a dataset's journey through the storage layers.
         */
        LayerStage: {
            /** Layer */
            layer: string;
            /** Label */
            label: string;
            /** Table */
            table?: string | null;
            /** Row Count */
            row_count: number;
            /** Purpose */
            purpose: string;
            /** Transition */
            transition: string;
        };
        /** Lineage */
        Lineage: {
            /** Dataset Version Id */
            dataset_version_id: string;
            /** Dataset Name */
            dataset_name: string;
            /** Source File */
            source_file: string;
            /** Edges */
            edges: components["schemas"]["LineageEdge"][];
        };
        /** LineageEdge */
        LineageEdge: {
            /** From Node */
            from_node: string;
            /** To Node */
            to_node: string;
            /** Edge Type */
            edge_type: string;
            /** Dataset Version Id */
            dataset_version_id: string;
        };
        /** MetricInfo */
        MetricInfo: {
            /** Metric Id */
            metric_id: string;
            /** Label */
            label: string;
            /** Unit */
            unit: string;
            /** Definition */
            definition: string;
            /** Allowed Dimensions */
            allowed_dimensions: string[];
            /** Required Dimensions */
            required_dimensions: string[];
            /** Forbidden Dimensions */
            forbidden_dimensions: string[];
            /** Requires Scope */
            requires_scope: string[];
            /** Default Aggregation */
            default_aggregation: string;
            /** Facts */
            facts: string[];
        };
        /**
         * NarrativeFactsResponse
         * @description Everything a narrative may assert, precomputed so the LLM does no maths.
         */
        NarrativeFactsResponse: {
            /** Headline */
            headline: {
                [key: string]: unknown;
            };
            /** Movement */
            movement?: {
                [key: string]: unknown;
            } | null;
            /** Leaders */
            leaders: {
                [key: string]: unknown;
            }[];
            /** Laggards */
            laggards: {
                [key: string]: unknown;
            }[];
            /** Largest Changes */
            largest_changes: {
                [key: string]: unknown;
            }[];
            /** Anomalies */
            anomalies: {
                [key: string]: unknown;
            }[];
            applied_context: components["schemas"]["AppliedContext"];
            /** Caveats */
            caveats: components["schemas"]["Caveat"][];
        };
        /** OrderBy */
        OrderBy: {
            /**
             * Field
             * @default value
             */
            field: string;
            /**
             * Direction
             * @default desc
             * @enum {string}
             */
            direction: "asc" | "desc";
        };
        /** Page[DatasetVersion] */
        Page_DatasetVersion_: {
            /** Items */
            items: components["schemas"]["DatasetVersion"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
        };
        /** Page[DimensionInfo] */
        Page_DimensionInfo_: {
            /** Items */
            items: components["schemas"]["DimensionInfo"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
        };
        /** Page[DimensionValue] */
        Page_DimensionValue_: {
            /** Items */
            items: components["schemas"]["DimensionValue"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
        };
        /** Page[IngestSchema] */
        Page_IngestSchema_: {
            /** Items */
            items: components["schemas"]["IngestSchema"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
        };
        /** Page[LayerStage] */
        Page_LayerStage_: {
            /** Items */
            items: components["schemas"]["LayerStage"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
        };
        /** Page[Lineage] */
        Page_Lineage_: {
            /** Items */
            items: components["schemas"]["Lineage"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
        };
        /** Page[MetricInfo] */
        Page_MetricInfo_: {
            /** Items */
            items: components["schemas"]["MetricInfo"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
        };
        /** Page[RuleSummary] */
        Page_RuleSummary_: {
            /** Items */
            items: components["schemas"]["RuleSummary"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
        };
        /** Page[ValidationFinding] */
        Page_ValidationFinding_: {
            /** Items */
            items: components["schemas"]["ValidationFinding"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
        };
        /**
         * Period
         * @description Inclusive agricultural-year range, e.g. 2022-23 to 2024-25.
         */
        Period: {
            /** From */
            from?: string | null;
            /** To */
            to?: string | null;
        };
        /** QueryResponse */
        QueryResponse: {
            /** Rows */
            rows: {
                [key: string]: unknown;
            }[];
            applied_context: components["schemas"]["AppliedContext"];
            /** Caveats */
            caveats: components["schemas"]["Caveat"][];
            /** Records */
            records?: {
                [key: string]: unknown;
            }[] | null;
        };
        /** QuerySpec */
        QuerySpec: {
            /** Metric */
            metric: string;
            /** Dimensions */
            dimensions?: string[];
            /** Filters */
            filters?: components["schemas"]["Filter"][];
            period?: components["schemas"]["Period"] | null;
            order_by?: components["schemas"]["OrderBy"] | null;
            /**
             * Limit
             * @default 100
             */
            limit: number;
            /**
             * Include Records
             * @default false
             */
            include_records: boolean;
        };
        /**
         * RecordsResponse
         * @description Drill-down: the fact rows behind a result cell.
         */
        RecordsResponse: {
            /** Records */
            records: {
                [key: string]: unknown;
            }[];
            /** Returned */
            returned: number;
            /** Total Matching */
            total_matching: number;
            /** Truncated */
            truncated: boolean;
            /** Source Datasets */
            source_datasets: components["schemas"]["SourceDataset"][];
        };
        /** RuleCount */
        RuleCount: {
            /** Rule Code */
            rule_code: string;
            /** Severity */
            severity: string;
            /** Count */
            count: number;
        };
        /**
         * RuleSummary
         * @description Findings for one rule within one dataset version.
         */
        RuleSummary: {
            /** Rule Code */
            rule_code: string;
            /** Severity */
            severity: string;
            /** Finding Count */
            finding_count: number;
            /** Sample Row Ref */
            sample_row_ref?: string | null;
            /** Sample Message */
            sample_message?: string | null;
            /** Column Count */
            column_count: number;
        };
        /** SourceDataset */
        SourceDataset: {
            /** Dataset Version Id */
            dataset_version_id: string;
            /** Dataset Name */
            dataset_name: string;
            /** Source File */
            source_file: string;
            /** Layer */
            layer: string;
        };
        /**
         * SpecErrorResponse
         * @description 422 body: machine-readable so a caller can correct itself and retry.
         */
        SpecErrorResponse: {
            /** Detail */
            detail: string;
            /** Code */
            code: string;
            /** Field */
            field: string;
            /** Allowed Values */
            allowed_values: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** ValidationFinding */
        ValidationFinding: {
            /** Run Id */
            run_id: string;
            /** Dataset Version Id */
            dataset_version_id: string;
            /** Rule Code */
            rule_code: string;
            /** Severity */
            severity: string;
            /** Row Ref */
            row_ref?: string | null;
            /** Column Name */
            column_name?: string | null;
            /** Message */
            message?: string | null;
            /** Observed Value */
            observed_value?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    list_datasets_datasets_get: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
                layer?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_DatasetVersion_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dataset_datasets__dataset_version_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_version_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetVersion"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dataset_validation_datasets__dataset_version_id__validation_get: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
                severity?: string | null;
                rule_code?: string | null;
            };
            header?: never;
            path: {
                dataset_version_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ValidationFinding_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dataset_layers_datasets__dataset_version_id__layers_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_version_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_LayerStage_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_validation_summary_datasets__dataset_version_id__validation_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_version_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_RuleSummary_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_lineage_for_many_lineage_get: {
        parameters: {
            query: {
                dataset_version_id: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_Lineage_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_lineage_lineage__dataset_version_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_version_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lineage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_ingest_schemas_ingest_schemas_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_IngestSchema_"];
                };
            };
        };
    };
    ingest_upload_ingest_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_ingest_upload_ingest_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_metrics_semantic_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_MetricInfo_"];
                };
            };
        };
    };
    list_dimensions_semantic_dimensions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_DimensionInfo_"];
                };
            };
        };
    };
    list_dimension_values_semantic_dimensions__dimension_id__values_get: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path: {
                dimension_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_DimensionValue_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_query_query_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuerySpec"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpecErrorResponse"];
                };
            };
        };
    };
    post_query_records_query_records_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuerySpec"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordsResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpecErrorResponse"];
                };
            };
        };
    };
    post_narrative_facts_query_narrative_facts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuerySpec"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NarrativeFactsResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpecErrorResponse"];
                };
            };
        };
    };
}
